apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: manual-run-1
  namespace: cicd
spec:
  serviceAccountName: pipeline-account
  pipelineRef:
    name: ci-cd-pipeline
  params:
    - name: git-url
      value: git@github.com:kusumaningrat/DevOps-Coding-Assessment.git
    - name: git-revision
      value: main
    - name: image-name
      value: docker.io/kusumaningrat16/ruby-backend-markeble
    - name: git-user-name
      value: kusumaningrat
    - name: git-user-email
      value: kusumanetcom@gmail.com
    - name: deployment-file
      value: git/deployment/app.yaml
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-shared-storage-pvc
    - name: ssh-creds
      secret:
        secretName: github-ssh-key
