apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: manual-run-1
  namespace: cicd
spec:
  serviceAccountName: pipeline-account
  pipelineRef:
    name: ci-cd-pipeline
  params:
    - name: git-url
      value: https://github.com/kusumaningrat/DevOps-Coding-Assessment.git
    - name: git-revision
      value: main
    - name: base-image-url
      value: docker.io/kusumaningrat16/ruby-backend-markeble
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-shared-storage-pvc
