apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-and-push
  namespace: cicd
spec:
  params:
    - name: image-name
    - name: image-tag
  workspaces:
    - name: shared-workspace
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
      args:
        - "--context=$(workspaces.shared-workspace.path)/git"
        - "--dockerfile=Dockerfile"
        - "--destination=$(params.image-name):$(params.image-tag)"
  volumes:
    - name: docker-config
      secret:
        secretName: docker-credentials
