apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: cicd
spec:
  params:
    - name: url
    - name: revision
  workspaces:
    - name: shared-workspace
    - name: ssh-creds
  steps:
    - name: clear-workspace
      image: alpine
      script: |
        #!/bin/sh
        echo "== Clearing git folder before clone =="
        rm -rf /workspace/shared-workspace/git || true
        mkdir -p /workspace/shared-workspace/git

    - name: setup-ssh
      image: alpine/git
      script: |
        #!/bin/sh
        mkdir -p /workspace/shared-workspace/.ssh
        cp /workspace/ssh-creds/ssh-privatekey /workspace/shared-workspace/.ssh/id_rsa
        chmod 600 /workspace/shared-workspace/.ssh/id_rsa

        ssh-keyscan github.com >> /workspace/shared-workspace/.ssh/known_hosts
        chmod 644 /workspace/shared-workspace/.ssh/known_hosts

        echo "Host github.com" >> /workspace/shared-workspace/.ssh/config
        echo "  StrictHostKeyChecking no" >> /workspace/shared-workspace/.ssh/config
        chmod 600 /workspace/shared-workspace/.ssh/config

    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        set -ex
        export GIT_SSH_COMMAND="ssh -i /workspace/shared-workspace/.ssh/id_rsa -o UserKnownHostsFile=/workspace/shared-workspace/.ssh/known_hosts -o StrictHostKeyChecking=no"
        git clone -b $(params.revision) $(params.url) /workspace/shared-workspace/git
