---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-shared-storage-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/tekton"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-shared-storage-pvc
  namespace: cicd
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi